#DiamondHunter made by Jwoolley
#
#To change the message for players with the right permission mode, change the part after Message:

Tag: [DH]

EmeraldMessage: mined a block of Emerald at location
DiamondMessage: mined a block of Diamond ore at location
RedstoneMessage: mined a block of Redstone at location
LapisMessage: mined a block of Lapis Lazuli at location
GoldMessage: mined a block of Gold ore at location
IronMessage: mined a block of Iron ore at location
CoalMessage: mined a block of Coal ore at location

EmeraldNotice: false
DiamondNotice: true
RedstoneNotice: false
LapisNotice: false
GoldNotice: false
IronNotice: false
CoalNotice: false

LogToFile: true

CreativeNotice: true