#DiamondHunter made by Jwoolley, for support visit the Bukkit or Spigot page
#
#If you wish to change the messages, then open up the messages.yml file

#The blocks you want to be logged when broken
blocks: 
  - diamond_ore
  - ancient_debris
  - emerald_ore
  - redstone_ore
  - lapis_ore
  - iron_ore
  - gold_ore
  - coal_ore

#Set to false if you don't want messages about blocks being broken in creative
logCreative: true

#Set to true if you wish to use MySQL
mysql: false

#Connection details for MySQL
hostname: 
port: 
database: 
username: 
password: 