name: DiamondHunter
main: com.github.Jwoolley.DiamondHunter
version: 2.0.3

commands:
  dh:
        description: Access to all the Diamond Hunter commands
        usage: /<command>
        permission: dh.reload

permissions:
    dh.getnotice:
         description: Gives the user the notices of when someone breaks a Diamond Ore
         default: op
    dh.reload:
         description: Allows the user to reload DiamondHunter
         default: op
    dh.exempt:
         description: Stops the user from announcing their mining
         default: op 